### PR TITLE
Add a copy of the BSD license so it can be forked and a README for discoverbility

### PR DESCRIPTION
**Pull request by rogersachan**
This pull request adds a copy of the BSD license to make this application open source. Source code without a license is still copyrighted and therefore cannot be forked and built on. I have also added a README so it is easier to find with GitHub's search engine.

### CODE REVIEW

**Comment by rogersachan** [comment]
@Mdashdotdashn Do I need to sign a CLA or the like to have my pull request merged?

**Comment by rogersachan** [comment]
@Mdashdotdashn Do I need to sign a CLA or the like to have my pull request merged?

**Comment by pdesaulniers** [comment]
+1! I think it would be very nice if this project had some clear licensing info!

@Mdashdotdashn, please consider merging this. I believe the PR is fine as it is :)

**Comment by Mdashdotdashn** [comment]
Merged ! Thanks.

**Pull request merged**
